# Generated by Django 5.2.4 on 2025-12-30 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='coin_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='note',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
