# Generated by Django 5.2.4 on 2025-12-30 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0003_userprofile_branch_userprofile_college'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='college',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='college_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
