# Generated by Django 6.0 on 2026-01-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0004_remove_userprofile_college_userprofile_college_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='mobile',
        ),
        migrations.AddField(
            model_name='otp',
            name='email',
            field=models.EmailField(default='dummy@edudiplomahub.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
